//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.05 at 06:32:19 PM EEST 
//
package gr.upatras.ceid.hpclab.response.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the gr.upatras.ceid.hpclab.response.model
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package:
     * gr.upatras.ceid.hpclab.response.model
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Results }
     *
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link CategoryType }
     *
     */
    public CategoryType createCategoryType() {
        return new CategoryType();
    }

    /**
     * Create an instance of {@link ResultType }
     *
     */
    public ResultType createResultType() {
        return new ResultType();
    }

    /**
     * Create an instance of {@link TranslationType }
     *
     */
    public TranslationType createTranslationType() {
        return new TranslationType();
    }

}
